org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

mod_version=0.1.0-alpha
mc_versions=1.21.1
maven_group=net.blopybox
archives_name=selfhosted-linkage
enabled_platforms=fabric,neoforge

minecraft_version=1.21.1
# compile against a conservative loader so older friend installs still work
fabric_loader_version=0.16.14
neoforge_version=21.1.250
